### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by peylight** [streetlogics/bombsquad_server#1]
Hello
I have debian 8.9 x64
When i run the server i see the error:
`
$ python bombsquad_server 
bombsquad server wrapper starting up...
tip: enter python commands via stdin to reconfigure the server on the fly:
example: config['partyName'] = 'New Party Name'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named time
Exception in game thread:
/mnt/hgfs/ericf/Documents/bombsquad/src/bsPython.cpp:6050: game thread : error: assert failed: result == 0

`

**Comment by peylight** [comment]
```
$ sudo python bombsquad_server -cfgdir config.py 
bombsquad server wrapper starting up...
tip: enter python commands via stdin to reconfigure the server on the fly:
example: config['partyName'] = 'New Party Name'
Traceback (most recent call last):
  File "bombsquad_server", line 136, in <module>
    result = subprocess.Popen([binaryPath,'-cfgdir','bscfg'], stdin=subprocess.PIPE)
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

```

**Comment by peylight** [comment]
```
$ cat config.py | sudo python bombsquad_server
Traceback (most recent call last):
  File "bombsquad_server", line 136, in <module>
    result = subprocess.Popen([binaryPath,'-cfgdir','bscfg'], stdin=subprocess.PIPE)
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

```
